MODEL_NAME_TO_POOL_TYPE = {
    'e5-small': 'avg',
    'e5-base': 'avg',
    'e5-large': 'avg',
    'e5-small-v2': 'avg',
    'e5-base-v2': 'avg',
    'e5-large-v2': 'avg',
    'multilingual-e5-small': 'avg',
    'multilingual-e5-base': 'avg',
    'multilingual-e5-large': 'avg',
    'e5-mistral-7b-instruct': 'last',
    'bge-large-en-v1.5': 'cls',
    'bge-base-en-v1.5': 'cls',
    'bge-m3': 'cls',
    "gte-large": "avg",
    "gte-base": "avg",
    "gte-base-pi-4k": "avg",
    "gte-base-pi-2k": "avg",
    "gte-base-pi-1k": "avg",
    'gte-base-4k-ipt': "avg",
    'gte-base-4k-ept': "avg",
    'm2-bert-80M-32k-retrieval': 'avg',
    'm2-bert-80M-2k-retrieval': 'avg',
    'nomic-embed-text-v1': 'avg'
}


MODEL_NAME_TO_PREFIX_TYPE = {
    'e5-small': 'query_or_passage',
    'e5-base': 'query_or_passage',
    'e5-large': 'query_or_passage',
    'e5-small-v2': 'query_or_passage',
    'e5-base-v2': 'query_or_passage',
    'e5-large-v2': 'query_or_passage',
    'multilingual-e5-small': 'query_or_passage',
    'multilingual-e5-base': 'query_or_passage',
    'multilingual-e5-large': 'query_or_passage',
    'e5-mistral-7b-instruct': 'instruction',
    "bge-large-en-v1.5": "bge",
    "bge-base-en-v1.5": "bge",
    'bge-m3': 'bge',
    "gte-large": "none",
    "gte-base": "none",
    "gte-base-pi-4k": "none",
    "gte-base-pi-2k": "none",
    "gte-base-pi-1k": "none",
    'gte-base-4k-ipt': "none",
    'gte-base-4k-ept': "none",
    'm2-bert-80M-32k-retrieval': 'none',
    'm2-bert-80M-2k-retrieval': 'none',
    'nomic-embed-text-v1': 'nomic'
}